version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      env_file:
        - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      env_file:
        - .env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
