### REGISTER USER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
   "fullName": "Imane Souaouti",
   "email": "souaouti.iman@gmail.com",
   "password": "Password@123!",
   "phoneNumber": "31267892390",
   "address": "1234 Elm Street, Springfield, IL, USA"
}

### LOGIN USER
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
   "email": "souaouti.iman@gmail.com",
   "password": "Password@123!"
}