name: Cinimaty Careers CI/CD

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      # Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the Project
      - name: Build
        run: npm run build

      # Run Tests
      - name: Run Tests
        run: npm test

      # Run Linter
      - name: Run Linter
        run: npm run lint
